org.opentest4j.AssertionFailedError: array contents differ at index [0][1], expected: <0> but was: <1> 	at io.github.tduncan.gameoflife.GameOfLifeTes.gridContainAllLiveCellsWillOnlyHaveCornersRemainingAlive(GameOfLifeTest.java:69)
Our next failing test! And our first scenario that requires a cells state change from one generation to the next. Lets start implementing the solution.